""" trigger/02000245_bf/trigger_03_02.xml """
from common import *
import state


class 대기(state.State):
    def on_enter(self):
        set_mesh(triggerIds=[801], visible=True, arg3=0, arg4=0, arg5=0)
        set_skill(triggerIds=[7001], isEnable=True)
        set_skill(triggerIds=[7002], isEnable=True)
        set_skill(triggerIds=[7003], isEnable=True)
        set_skill(triggerIds=[7004], isEnable=True)
        set_skill(triggerIds=[7005], isEnable=True)
        set_skill(triggerIds=[7006], isEnable=True)
        set_skill(triggerIds=[7007], isEnable=True)
        set_skill(triggerIds=[7008], isEnable=True)
        set_skill(triggerIds=[7009], isEnable=True)
        set_skill(triggerIds=[7010], isEnable=True)
        set_skill(triggerIds=[7011], isEnable=True)
        set_skill(triggerIds=[7012], isEnable=True)
        set_skill(triggerIds=[7013], isEnable=True)
        set_skill(triggerIds=[7014], isEnable=True)
        set_skill(triggerIds=[7015], isEnable=True)
        set_skill(triggerIds=[7016], isEnable=True)
        set_skill(triggerIds=[7017], isEnable=True)
        set_skill(triggerIds=[7018], isEnable=True)
        set_skill(triggerIds=[7019], isEnable=True)
        set_skill(triggerIds=[7020], isEnable=True)
        set_effect(triggerIds=[901], visible=True)
        set_effect(triggerIds=[902], visible=True)
        set_effect(triggerIds=[903], visible=True)
        set_effect(triggerIds=[904], visible=True)
        set_effect(triggerIds=[905], visible=True)
        set_effect(triggerIds=[906], visible=True)
        set_effect(triggerIds=[907], visible=True)
        set_effect(triggerIds=[908], visible=True)
        set_effect(triggerIds=[909], visible=True)
        set_effect(triggerIds=[910], visible=True)
        set_effect(triggerIds=[911], visible=True)
        set_effect(triggerIds=[912], visible=True)
        set_effect(triggerIds=[913], visible=True)
        set_effect(triggerIds=[914], visible=True)
        set_effect(triggerIds=[915], visible=True)
        set_effect(triggerIds=[916], visible=True)
        set_effect(triggerIds=[917], visible=True)
        set_effect(triggerIds=[918], visible=True)
        set_effect(triggerIds=[919], visible=True)
        set_effect(triggerIds=[920], visible=True)

    def on_tick(self) -> state.State:
        if user_detected(boxIds=[207]):
            return 단계1()


class 단계1(state.State):
    def on_enter(self):
        set_mesh(triggerIds=[801], visible=False, arg3=0, arg4=0, arg5=0)
        set_skill(triggerIds=[7001], isEnable=False)
        set_skill(triggerIds=[7002], isEnable=False)
        set_skill(triggerIds=[7003], isEnable=False)
        set_skill(triggerIds=[7004], isEnable=False)
        set_skill(triggerIds=[7005], isEnable=False)
        set_skill(triggerIds=[7006], isEnable=False)
        set_skill(triggerIds=[7007], isEnable=False)
        set_skill(triggerIds=[7008], isEnable=False)
        set_skill(triggerIds=[7009], isEnable=False)
        set_skill(triggerIds=[7010], isEnable=False)
        set_skill(triggerIds=[7011], isEnable=False)
        set_skill(triggerIds=[7012], isEnable=False)
        set_skill(triggerIds=[7013], isEnable=False)
        set_skill(triggerIds=[7014], isEnable=False)
        set_skill(triggerIds=[7015], isEnable=False)
        set_skill(triggerIds=[7016], isEnable=False)
        set_skill(triggerIds=[7017], isEnable=False)
        set_skill(triggerIds=[7018], isEnable=False)
        set_skill(triggerIds=[7019], isEnable=False)
        set_skill(triggerIds=[7020], isEnable=False)
        set_effect(triggerIds=[901], visible=False)
        set_effect(triggerIds=[902], visible=False)
        set_effect(triggerIds=[903], visible=False)
        set_effect(triggerIds=[904], visible=False)
        set_effect(triggerIds=[905], visible=False)
        set_effect(triggerIds=[906], visible=False)
        set_effect(triggerIds=[907], visible=False)
        set_effect(triggerIds=[908], visible=False)
        set_effect(triggerIds=[909], visible=False)
        set_effect(triggerIds=[910], visible=False)
        set_effect(triggerIds=[911], visible=False)
        set_effect(triggerIds=[912], visible=False)
        set_effect(triggerIds=[913], visible=False)
        set_effect(triggerIds=[914], visible=False)
        set_effect(triggerIds=[915], visible=False)
        set_effect(triggerIds=[916], visible=False)
        set_effect(triggerIds=[917], visible=False)
        set_effect(triggerIds=[918], visible=False)
        set_effect(triggerIds=[919], visible=False)
        set_effect(triggerIds=[920], visible=False)


