""" trigger/02000245_bf/trigger_01_02.xml """
from common import *
import state


class 대기(state.State):
    def on_enter(self):
        set_mesh(triggerIds=[802], visible=True, arg3=0, arg4=0, arg5=0)
        set_skill(triggerIds=[7021], isEnable=True)
        set_skill(triggerIds=[7022], isEnable=True)
        set_skill(triggerIds=[7023], isEnable=True)
        set_skill(triggerIds=[7024], isEnable=True)
        set_skill(triggerIds=[7025], isEnable=True)
        set_skill(triggerIds=[7026], isEnable=True)
        set_skill(triggerIds=[7027], isEnable=True)
        set_skill(triggerIds=[7028], isEnable=True)
        set_skill(triggerIds=[7029], isEnable=True)
        set_skill(triggerIds=[7030], isEnable=True)
        set_skill(triggerIds=[7031], isEnable=True)
        set_skill(triggerIds=[7032], isEnable=True)
        set_skill(triggerIds=[7033], isEnable=True)
        set_skill(triggerIds=[7034], isEnable=True)
        set_skill(triggerIds=[7035], isEnable=True)
        set_skill(triggerIds=[7036], isEnable=True)
        set_skill(triggerIds=[7037], isEnable=True)
        set_skill(triggerIds=[7038], isEnable=True)
        set_skill(triggerIds=[7039], isEnable=True)
        set_skill(triggerIds=[7040], isEnable=True)
        set_effect(triggerIds=[921], visible=True)
        set_effect(triggerIds=[922], visible=True)
        set_effect(triggerIds=[923], visible=True)
        set_effect(triggerIds=[924], visible=True)
        set_effect(triggerIds=[925], visible=True)
        set_effect(triggerIds=[926], visible=True)
        set_effect(triggerIds=[927], visible=True)
        set_effect(triggerIds=[928], visible=True)
        set_effect(triggerIds=[929], visible=True)
        set_effect(triggerIds=[930], visible=True)
        set_effect(triggerIds=[931], visible=True)
        set_effect(triggerIds=[932], visible=True)
        set_effect(triggerIds=[933], visible=True)
        set_effect(triggerIds=[934], visible=True)
        set_effect(triggerIds=[935], visible=True)
        set_effect(triggerIds=[936], visible=True)
        set_effect(triggerIds=[937], visible=True)
        set_effect(triggerIds=[938], visible=True)
        set_effect(triggerIds=[939], visible=True)
        set_effect(triggerIds=[940], visible=True)

    def on_tick(self) -> state.State:
        if user_detected(boxIds=[208]):
            return 단계1()


class 단계1(state.State):
    def on_enter(self):
        set_mesh(triggerIds=[802], visible=False, arg3=0, arg4=0, arg5=0)
        set_skill(triggerIds=[7021], isEnable=False)
        set_skill(triggerIds=[7022], isEnable=False)
        set_skill(triggerIds=[7023], isEnable=False)
        set_skill(triggerIds=[7024], isEnable=False)
        set_skill(triggerIds=[7025], isEnable=False)
        set_skill(triggerIds=[7026], isEnable=False)
        set_skill(triggerIds=[7027], isEnable=False)
        set_skill(triggerIds=[7028], isEnable=False)
        set_skill(triggerIds=[7029], isEnable=False)
        set_skill(triggerIds=[7030], isEnable=False)
        set_skill(triggerIds=[7031], isEnable=False)
        set_skill(triggerIds=[7032], isEnable=False)
        set_skill(triggerIds=[7033], isEnable=False)
        set_skill(triggerIds=[7034], isEnable=False)
        set_skill(triggerIds=[7035], isEnable=False)
        set_skill(triggerIds=[7036], isEnable=False)
        set_skill(triggerIds=[7037], isEnable=False)
        set_skill(triggerIds=[7038], isEnable=False)
        set_skill(triggerIds=[7039], isEnable=False)
        set_skill(triggerIds=[7040], isEnable=False)
        set_effect(triggerIds=[921], visible=False)
        set_effect(triggerIds=[922], visible=False)
        set_effect(triggerIds=[923], visible=False)
        set_effect(triggerIds=[924], visible=False)
        set_effect(triggerIds=[925], visible=False)
        set_effect(triggerIds=[926], visible=False)
        set_effect(triggerIds=[927], visible=False)
        set_effect(triggerIds=[928], visible=False)
        set_effect(triggerIds=[929], visible=False)
        set_effect(triggerIds=[930], visible=False)
        set_effect(triggerIds=[931], visible=False)
        set_effect(triggerIds=[932], visible=False)
        set_effect(triggerIds=[933], visible=False)
        set_effect(triggerIds=[934], visible=False)
        set_effect(triggerIds=[935], visible=False)
        set_effect(triggerIds=[936], visible=False)
        set_effect(triggerIds=[937], visible=False)
        set_effect(triggerIds=[938], visible=False)
        set_effect(triggerIds=[939], visible=False)
        set_effect(triggerIds=[940], visible=False)


