""" trigger/02000245_bf/trigger_01_02.xml """
import common


class 대기(common.Trigger):
    def on_enter(self):
        self.set_mesh(triggerIds=[802], visible=True, arg3=0, delay=0, scale=0)
        self.set_skill(triggerIds=[7021], enable=True)
        self.set_skill(triggerIds=[7022], enable=True)
        self.set_skill(triggerIds=[7023], enable=True)
        self.set_skill(triggerIds=[7024], enable=True)
        self.set_skill(triggerIds=[7025], enable=True)
        self.set_skill(triggerIds=[7026], enable=True)
        self.set_skill(triggerIds=[7027], enable=True)
        self.set_skill(triggerIds=[7028], enable=True)
        self.set_skill(triggerIds=[7029], enable=True)
        self.set_skill(triggerIds=[7030], enable=True)
        self.set_skill(triggerIds=[7031], enable=True)
        self.set_skill(triggerIds=[7032], enable=True)
        self.set_skill(triggerIds=[7033], enable=True)
        self.set_skill(triggerIds=[7034], enable=True)
        self.set_skill(triggerIds=[7035], enable=True)
        self.set_skill(triggerIds=[7036], enable=True)
        self.set_skill(triggerIds=[7037], enable=True)
        self.set_skill(triggerIds=[7038], enable=True)
        self.set_skill(triggerIds=[7039], enable=True)
        self.set_skill(triggerIds=[7040], enable=True)
        self.set_effect(triggerIds=[921], visible=True)
        self.set_effect(triggerIds=[922], visible=True)
        self.set_effect(triggerIds=[923], visible=True)
        self.set_effect(triggerIds=[924], visible=True)
        self.set_effect(triggerIds=[925], visible=True)
        self.set_effect(triggerIds=[926], visible=True)
        self.set_effect(triggerIds=[927], visible=True)
        self.set_effect(triggerIds=[928], visible=True)
        self.set_effect(triggerIds=[929], visible=True)
        self.set_effect(triggerIds=[930], visible=True)
        self.set_effect(triggerIds=[931], visible=True)
        self.set_effect(triggerIds=[932], visible=True)
        self.set_effect(triggerIds=[933], visible=True)
        self.set_effect(triggerIds=[934], visible=True)
        self.set_effect(triggerIds=[935], visible=True)
        self.set_effect(triggerIds=[936], visible=True)
        self.set_effect(triggerIds=[937], visible=True)
        self.set_effect(triggerIds=[938], visible=True)
        self.set_effect(triggerIds=[939], visible=True)
        self.set_effect(triggerIds=[940], visible=True)

    def on_tick(self) -> common.Trigger:
        if self.user_detected(boxIds=[208]):
            return 단계1(self.ctx)


class 단계1(common.Trigger):
    def on_enter(self):
        self.set_mesh(triggerIds=[802], visible=False, arg3=0, delay=0, scale=0)
        self.set_skill(triggerIds=[7021], enable=False)
        self.set_skill(triggerIds=[7022], enable=False)
        self.set_skill(triggerIds=[7023], enable=False)
        self.set_skill(triggerIds=[7024], enable=False)
        self.set_skill(triggerIds=[7025], enable=False)
        self.set_skill(triggerIds=[7026], enable=False)
        self.set_skill(triggerIds=[7027], enable=False)
        self.set_skill(triggerIds=[7028], enable=False)
        self.set_skill(triggerIds=[7029], enable=False)
        self.set_skill(triggerIds=[7030], enable=False)
        self.set_skill(triggerIds=[7031], enable=False)
        self.set_skill(triggerIds=[7032], enable=False)
        self.set_skill(triggerIds=[7033], enable=False)
        self.set_skill(triggerIds=[7034], enable=False)
        self.set_skill(triggerIds=[7035], enable=False)
        self.set_skill(triggerIds=[7036], enable=False)
        self.set_skill(triggerIds=[7037], enable=False)
        self.set_skill(triggerIds=[7038], enable=False)
        self.set_skill(triggerIds=[7039], enable=False)
        self.set_skill(triggerIds=[7040], enable=False)
        self.set_effect(triggerIds=[921], visible=False)
        self.set_effect(triggerIds=[922], visible=False)
        self.set_effect(triggerIds=[923], visible=False)
        self.set_effect(triggerIds=[924], visible=False)
        self.set_effect(triggerIds=[925], visible=False)
        self.set_effect(triggerIds=[926], visible=False)
        self.set_effect(triggerIds=[927], visible=False)
        self.set_effect(triggerIds=[928], visible=False)
        self.set_effect(triggerIds=[929], visible=False)
        self.set_effect(triggerIds=[930], visible=False)
        self.set_effect(triggerIds=[931], visible=False)
        self.set_effect(triggerIds=[932], visible=False)
        self.set_effect(triggerIds=[933], visible=False)
        self.set_effect(triggerIds=[934], visible=False)
        self.set_effect(triggerIds=[935], visible=False)
        self.set_effect(triggerIds=[936], visible=False)
        self.set_effect(triggerIds=[937], visible=False)
        self.set_effect(triggerIds=[938], visible=False)
        self.set_effect(triggerIds=[939], visible=False)
        self.set_effect(triggerIds=[940], visible=False)


initial_state = 대기
