""" trigger/02000245_bf/trigger_03_02.xml """
import trigger_api


class 대기(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_mesh(trigger_ids=[801], visible=True, start_delay=0, interval=0, fade=0)
        self.set_skill(trigger_ids=[7001], enable=True)
        self.set_skill(trigger_ids=[7002], enable=True)
        self.set_skill(trigger_ids=[7003], enable=True)
        self.set_skill(trigger_ids=[7004], enable=True)
        self.set_skill(trigger_ids=[7005], enable=True)
        self.set_skill(trigger_ids=[7006], enable=True)
        self.set_skill(trigger_ids=[7007], enable=True)
        self.set_skill(trigger_ids=[7008], enable=True)
        self.set_skill(trigger_ids=[7009], enable=True)
        self.set_skill(trigger_ids=[7010], enable=True)
        self.set_skill(trigger_ids=[7011], enable=True)
        self.set_skill(trigger_ids=[7012], enable=True)
        self.set_skill(trigger_ids=[7013], enable=True)
        self.set_skill(trigger_ids=[7014], enable=True)
        self.set_skill(trigger_ids=[7015], enable=True)
        self.set_skill(trigger_ids=[7016], enable=True)
        self.set_skill(trigger_ids=[7017], enable=True)
        self.set_skill(trigger_ids=[7018], enable=True)
        self.set_skill(trigger_ids=[7019], enable=True)
        self.set_skill(trigger_ids=[7020], enable=True)
        self.set_effect(trigger_ids=[901], visible=True)
        self.set_effect(trigger_ids=[902], visible=True)
        self.set_effect(trigger_ids=[903], visible=True)
        self.set_effect(trigger_ids=[904], visible=True)
        self.set_effect(trigger_ids=[905], visible=True)
        self.set_effect(trigger_ids=[906], visible=True)
        self.set_effect(trigger_ids=[907], visible=True)
        self.set_effect(trigger_ids=[908], visible=True)
        self.set_effect(trigger_ids=[909], visible=True)
        self.set_effect(trigger_ids=[910], visible=True)
        self.set_effect(trigger_ids=[911], visible=True)
        self.set_effect(trigger_ids=[912], visible=True)
        self.set_effect(trigger_ids=[913], visible=True)
        self.set_effect(trigger_ids=[914], visible=True)
        self.set_effect(trigger_ids=[915], visible=True)
        self.set_effect(trigger_ids=[916], visible=True)
        self.set_effect(trigger_ids=[917], visible=True)
        self.set_effect(trigger_ids=[918], visible=True)
        self.set_effect(trigger_ids=[919], visible=True)
        self.set_effect(trigger_ids=[920], visible=True)

    def on_tick(self) -> trigger_api.Trigger:
        if self.user_detected(box_ids=[207]):
            return 단계1(self.ctx)


class 단계1(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_mesh(trigger_ids=[801], visible=False, start_delay=0, interval=0, fade=0)
        self.set_skill(trigger_ids=[7001], enable=False)
        self.set_skill(trigger_ids=[7002], enable=False)
        self.set_skill(trigger_ids=[7003], enable=False)
        self.set_skill(trigger_ids=[7004], enable=False)
        self.set_skill(trigger_ids=[7005], enable=False)
        self.set_skill(trigger_ids=[7006], enable=False)
        self.set_skill(trigger_ids=[7007], enable=False)
        self.set_skill(trigger_ids=[7008], enable=False)
        self.set_skill(trigger_ids=[7009], enable=False)
        self.set_skill(trigger_ids=[7010], enable=False)
        self.set_skill(trigger_ids=[7011], enable=False)
        self.set_skill(trigger_ids=[7012], enable=False)
        self.set_skill(trigger_ids=[7013], enable=False)
        self.set_skill(trigger_ids=[7014], enable=False)
        self.set_skill(trigger_ids=[7015], enable=False)
        self.set_skill(trigger_ids=[7016], enable=False)
        self.set_skill(trigger_ids=[7017], enable=False)
        self.set_skill(trigger_ids=[7018], enable=False)
        self.set_skill(trigger_ids=[7019], enable=False)
        self.set_skill(trigger_ids=[7020], enable=False)
        self.set_effect(trigger_ids=[901], visible=False)
        self.set_effect(trigger_ids=[902], visible=False)
        self.set_effect(trigger_ids=[903], visible=False)
        self.set_effect(trigger_ids=[904], visible=False)
        self.set_effect(trigger_ids=[905], visible=False)
        self.set_effect(trigger_ids=[906], visible=False)
        self.set_effect(trigger_ids=[907], visible=False)
        self.set_effect(trigger_ids=[908], visible=False)
        self.set_effect(trigger_ids=[909], visible=False)
        self.set_effect(trigger_ids=[910], visible=False)
        self.set_effect(trigger_ids=[911], visible=False)
        self.set_effect(trigger_ids=[912], visible=False)
        self.set_effect(trigger_ids=[913], visible=False)
        self.set_effect(trigger_ids=[914], visible=False)
        self.set_effect(trigger_ids=[915], visible=False)
        self.set_effect(trigger_ids=[916], visible=False)
        self.set_effect(trigger_ids=[917], visible=False)
        self.set_effect(trigger_ids=[918], visible=False)
        self.set_effect(trigger_ids=[919], visible=False)
        self.set_effect(trigger_ids=[920], visible=False)


initial_state = 대기
