""" trigger/02000318_bf/shipmove_02.xml """
from common import *
import state


class Setting(state.State):
    def on_enter(self):
        set_interact_object(triggerIds=[10001046], state=0) # Wheel
        set_skill(triggerIds=[7000], isEnable=False)
        set_effect(triggerIds=[6000], visible=False)
        set_effect(triggerIds=[6001], visible=False)
        set_breakable(triggerIds=[4000], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4001], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4002], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4003], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4004], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4005], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4006], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4007], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4008], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4009], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4010], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4011], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4012], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4013], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4014], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4015], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4016], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4017], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4018], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4019], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4020], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4021], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4022], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4023], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4024], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4025], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4026], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4027], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4028], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4029], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4030], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4031], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4032], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4033], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4034], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4035], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4036], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4037], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4038], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4039], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4040], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4041], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4042], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4043], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4044], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4045], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4046], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4047], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4048], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4049], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4050], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4051], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4052], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4053], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4054], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4055], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4056], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4057], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4058], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4059], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4060], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4061], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4062], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4063], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4064], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4065], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4066], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4067], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4068], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4069], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4070], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4071], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4072], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4073], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4074], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4075], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4076], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4077], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4078], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4079], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4080], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4081], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4082], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4083], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4084], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4085], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4086], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4087], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4088], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4089], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4090], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4091], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4092], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4093], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4094], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4095], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4096], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4097], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4098], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4099], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4100], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4101], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4102], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4103], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4104], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4105], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4106], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4107], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4108], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4109], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4110], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4111], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4112], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4113], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4114], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4115], enabled=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4000], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4001], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4002], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4003], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4004], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4005], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4006], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4007], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4008], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4009], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4010], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4011], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4012], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4013], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4014], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4015], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4016], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4017], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4018], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4019], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4020], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4021], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4022], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4023], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4024], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4025], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4026], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4027], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4028], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4029], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4030], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4031], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4032], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4033], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4034], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4035], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4036], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4037], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4038], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4039], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4040], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4041], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4042], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4043], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4044], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4045], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4046], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4047], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4048], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4049], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4050], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4051], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4052], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4053], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4054], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4055], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4056], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4057], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4058], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4059], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4060], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4061], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4062], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4063], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4064], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4065], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4066], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4067], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4068], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4069], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4070], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4071], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4072], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4073], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4074], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4075], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4076], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4077], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4078], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4079], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4080], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4081], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4082], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4083], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4084], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4085], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4086], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4087], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4088], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4089], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4090], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4091], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4092], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4093], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4094], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4095], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4096], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4097], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4098], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4099], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4100], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4101], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4102], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4103], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4104], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4105], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4106], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4107], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4108], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4109], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4110], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4111], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4112], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4113], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4114], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4115], arg2=False) # Move_Ship
        set_user_value(key='ShipSet', value=0)

    def on_tick(self) -> state.State:
        if user_value(key='ShipSet', value=1):
            return MoveShip01()


class MoveShip01(state.State):
    def on_enter(self):
        set_visible_breakable_object(triggerIds=[4000], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4001], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4002], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4003], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4004], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4005], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4006], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4007], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4008], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4009], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4010], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4011], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4012], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4013], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4014], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4015], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4016], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4017], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4018], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4019], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4020], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4021], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4022], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4023], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4024], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4025], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4026], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4027], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4028], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4029], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4030], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4031], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4032], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4033], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4034], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4035], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4036], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4037], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4038], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4039], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4040], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4041], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4042], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4043], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4044], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4045], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4046], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4047], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4048], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4049], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4050], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4051], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4052], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4053], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4054], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4055], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4056], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4057], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4058], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4059], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4060], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4061], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4062], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4063], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4064], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4065], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4066], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4067], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4068], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4069], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4070], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4071], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4072], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4073], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4074], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4075], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4076], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4077], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4078], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4079], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4080], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4081], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4082], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4083], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4084], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4085], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4086], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4087], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4088], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4089], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4090], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4091], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4092], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4093], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4094], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4095], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4096], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4097], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4098], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4099], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4100], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4101], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4102], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4103], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4104], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4105], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4106], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4107], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4108], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4109], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4110], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4111], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4112], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4113], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4114], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4115], arg2=True) # Move_Ship
        set_interact_object(triggerIds=[10001046], state=1) # Wheel
        play_system_sound_in_box(boxIds=[102], sound='System_ShowGuideSummary_01')
        show_guide_summary(entityId=20031803, textId=20031803) # 키를 작동시켜 배를 움직이면 다음 지역으로 넘어갈 수 있습니다

    def on_tick(self) -> state.State:
        if object_interacted(interactIds=[10001046], arg2=0):
            return ShipMove02()


class ShipMove02(state.State):
    def on_enter(self):
        set_effect(triggerIds=[6001], visible=True)
        hide_guide_summary(entityId=20031803)
        set_user_value(triggerId=1, key='ShipMove', value=1)
        set_breakable(triggerIds=[4000], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4001], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4002], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4003], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4004], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4005], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4006], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4007], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4008], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4009], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4010], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4011], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4012], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4013], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4014], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4015], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4016], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4017], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4018], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4019], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4020], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4021], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4022], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4023], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4024], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4025], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4026], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4027], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4028], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4029], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4030], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4031], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4032], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4033], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4034], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4035], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4036], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4037], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4038], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4039], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4040], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4041], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4042], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4043], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4044], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4045], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4046], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4047], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4048], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4049], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4050], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4051], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4052], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4053], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4054], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4055], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4056], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4057], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4058], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4059], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4060], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4061], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4062], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4063], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4064], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4065], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4066], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4067], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4068], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4069], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4070], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4071], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4072], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4073], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4074], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4075], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4076], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4077], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4078], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4079], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4080], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4081], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4082], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4083], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4084], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4085], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4086], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4087], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4088], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4089], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4090], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4091], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4092], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4093], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4094], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4095], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4096], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4097], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4098], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4099], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4100], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4101], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4102], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4103], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4104], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4105], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4106], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4107], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4108], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4109], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4110], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4111], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4112], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4113], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4114], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4115], enabled=True) # Move_Ship

    def on_tick(self) -> state.State:
        if wait_tick(waitTick=3000):
            return ShipMove03()


class ShipMove03(state.State):
    def on_enter(self):
        set_effect(triggerIds=[6001], visible=False)
        set_skill(triggerIds=[7000], isEnable=True)
        set_effect(triggerIds=[6000], visible=True)

    def on_tick(self) -> state.State:
        if wait_tick(waitTick=19000):
            return ResetShip00()


class ResetShip00(state.State):
    def on_enter(self):
        set_interact_object(triggerIds=[10001046], state=0) # Wheel
        set_breakable(triggerIds=[4000], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4001], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4002], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4003], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4004], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4005], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4006], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4007], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4008], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4009], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4010], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4011], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4012], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4013], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4014], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4015], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4016], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4017], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4018], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4019], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4020], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4021], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4022], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4023], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4024], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4025], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4026], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4027], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4028], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4029], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4030], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4031], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4032], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4033], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4034], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4035], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4036], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4037], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4038], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4039], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4040], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4041], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4042], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4043], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4044], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4045], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4046], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4047], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4048], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4049], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4050], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4051], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4052], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4053], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4054], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4055], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4056], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4057], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4058], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4059], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4060], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4061], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4062], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4063], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4064], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4065], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4066], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4067], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4068], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4069], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4070], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4071], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4072], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4073], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4074], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4075], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4076], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4077], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4078], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4079], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4080], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4081], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4082], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4083], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4084], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4085], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4086], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4087], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4088], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4089], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4090], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4091], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4092], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4093], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4094], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4095], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4096], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4097], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4098], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4099], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4100], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4101], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4102], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4103], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4104], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4105], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4106], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4107], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4108], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4109], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4110], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4111], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4112], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4113], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4114], enabled=False) # Move_Ship
        set_breakable(triggerIds=[4115], enabled=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4000], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4001], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4002], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4003], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4004], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4005], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4006], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4007], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4008], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4009], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4010], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4011], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4012], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4013], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4014], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4015], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4016], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4017], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4018], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4019], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4020], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4021], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4022], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4023], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4024], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4025], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4026], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4027], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4028], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4029], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4030], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4031], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4032], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4033], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4034], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4035], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4036], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4037], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4038], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4039], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4040], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4041], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4042], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4043], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4044], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4045], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4046], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4047], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4048], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4049], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4050], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4051], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4052], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4053], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4054], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4055], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4056], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4057], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4058], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4059], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4060], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4061], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4062], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4063], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4064], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4065], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4066], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4067], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4068], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4069], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4070], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4071], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4072], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4073], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4074], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4075], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4076], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4077], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4078], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4079], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4080], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4081], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4082], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4083], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4084], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4085], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4086], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4087], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4088], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4089], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4090], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4091], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4092], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4093], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4094], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4095], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4096], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4097], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4098], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4099], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4100], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4101], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4102], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4103], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4104], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4105], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4106], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4107], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4108], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4109], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4110], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4111], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4112], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4113], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4114], arg2=False) # Move_Ship
        set_visible_breakable_object(triggerIds=[4115], arg2=False) # Move_Ship

    def on_tick(self) -> state.State:
        if wait_tick(waitTick=2000):
            return ResetShip01()


class ResetShip01(state.State):
    def on_enter(self):
        set_visible_breakable_object(triggerIds=[4000], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4001], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4002], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4003], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4004], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4005], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4006], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4007], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4008], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4009], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4010], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4011], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4012], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4013], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4014], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4015], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4016], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4017], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4018], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4019], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4020], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4021], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4022], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4023], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4024], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4025], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4026], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4027], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4028], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4029], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4030], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4031], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4032], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4033], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4034], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4035], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4036], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4037], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4038], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4039], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4040], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4041], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4042], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4043], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4044], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4045], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4046], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4047], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4048], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4049], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4050], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4051], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4052], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4053], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4054], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4055], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4056], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4057], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4058], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4059], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4060], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4061], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4062], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4063], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4064], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4065], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4066], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4067], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4068], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4069], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4070], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4071], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4072], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4073], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4074], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4075], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4076], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4077], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4078], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4079], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4080], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4081], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4082], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4083], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4084], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4085], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4086], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4087], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4088], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4089], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4090], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4091], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4092], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4093], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4094], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4095], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4096], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4097], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4098], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4099], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4100], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4101], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4102], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4103], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4104], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4105], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4106], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4107], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4108], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4109], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4110], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4111], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4112], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4113], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4114], arg2=True) # Move_Ship
        set_visible_breakable_object(triggerIds=[4115], arg2=True) # Move_Ship
        set_interact_object(triggerIds=[10001046], state=1) # Wheel

    def on_tick(self) -> state.State:
        if object_interacted(interactIds=[10001046], arg2=0):
            return ResetShip02()


class ResetShip02(state.State):
    def on_enter(self):
        set_breakable(triggerIds=[4000], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4001], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4002], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4003], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4004], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4005], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4006], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4007], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4008], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4009], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4010], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4011], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4012], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4013], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4014], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4015], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4016], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4017], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4018], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4019], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4020], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4021], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4022], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4023], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4024], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4025], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4026], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4027], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4028], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4029], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4030], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4031], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4032], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4033], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4034], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4035], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4036], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4037], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4038], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4039], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4040], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4041], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4042], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4043], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4044], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4045], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4046], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4047], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4048], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4049], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4050], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4051], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4052], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4053], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4054], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4055], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4056], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4057], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4058], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4059], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4060], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4061], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4062], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4063], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4064], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4065], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4066], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4067], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4068], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4069], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4070], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4071], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4072], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4073], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4074], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4075], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4076], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4077], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4078], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4079], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4080], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4081], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4082], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4083], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4084], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4085], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4086], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4087], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4088], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4089], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4090], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4091], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4092], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4093], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4094], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4095], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4096], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4097], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4098], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4099], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4100], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4101], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4102], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4103], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4104], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4105], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4106], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4107], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4108], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4109], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4110], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4111], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4112], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4113], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4114], enabled=True) # Move_Ship
        set_breakable(triggerIds=[4115], enabled=True) # Move_Ship

    def on_tick(self) -> state.State:
        if wait_tick(waitTick=24000):
            return ResetShip01()


