""" trigger/02000318_bf/shipmove_02.xml """
import trigger_api


class Setting(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_interact_object(trigger_ids=[10001046], state=0) # Wheel
        self.set_skill(trigger_ids=[7000], enable=False)
        self.set_effect(trigger_ids=[6000], visible=False)
        self.set_effect(trigger_ids=[6001], visible=False)
        self.set_breakable(trigger_ids=[4000], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4001], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4002], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4003], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4004], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4005], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4006], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4007], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4008], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4009], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4010], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4011], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4012], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4013], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4014], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4015], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4016], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4017], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4018], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4019], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4020], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4021], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4022], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4023], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4024], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4025], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4026], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4027], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4028], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4029], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4030], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4031], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4032], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4033], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4034], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4035], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4036], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4037], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4038], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4039], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4040], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4041], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4042], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4043], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4044], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4045], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4046], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4047], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4048], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4049], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4050], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4051], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4052], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4053], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4054], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4055], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4056], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4057], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4058], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4059], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4060], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4061], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4062], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4063], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4064], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4065], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4066], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4067], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4068], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4069], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4070], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4071], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4072], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4073], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4074], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4075], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4076], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4077], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4078], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4079], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4080], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4081], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4082], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4083], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4084], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4085], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4086], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4087], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4088], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4089], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4090], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4091], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4092], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4093], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4094], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4095], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4096], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4097], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4098], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4099], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4100], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4101], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4102], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4103], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4104], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4105], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4106], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4107], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4108], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4109], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4110], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4111], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4112], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4113], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4114], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4115], enable=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4000], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4001], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4002], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4003], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4004], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4005], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4006], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4007], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4008], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4009], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4010], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4011], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4012], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4013], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4014], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4015], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4016], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4017], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4018], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4019], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4020], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4021], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4022], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4023], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4024], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4025], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4026], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4027], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4028], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4029], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4030], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4031], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4032], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4033], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4034], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4035], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4036], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4037], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4038], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4039], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4040], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4041], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4042], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4043], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4044], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4045], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4046], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4047], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4048], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4049], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4050], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4051], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4052], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4053], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4054], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4055], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4056], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4057], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4058], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4059], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4060], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4061], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4062], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4063], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4064], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4065], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4066], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4067], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4068], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4069], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4070], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4071], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4072], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4073], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4074], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4075], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4076], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4077], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4078], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4079], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4080], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4081], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4082], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4083], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4084], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4085], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4086], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4087], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4088], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4089], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4090], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4091], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4092], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4093], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4094], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4095], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4096], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4097], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4098], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4099], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4100], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4101], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4102], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4103], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4104], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4105], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4106], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4107], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4108], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4109], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4110], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4111], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4112], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4113], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4114], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4115], visible=False) # Move_Ship
        self.set_user_value(key='ShipSet', value=0)

    def on_tick(self) -> trigger_api.Trigger:
        if self.user_value(key='ShipSet', value=1):
            return MoveShip01(self.ctx)


class MoveShip01(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_visible_breakable_object(trigger_ids=[4000], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4001], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4002], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4003], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4004], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4005], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4006], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4007], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4008], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4009], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4010], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4011], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4012], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4013], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4014], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4015], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4016], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4017], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4018], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4019], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4020], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4021], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4022], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4023], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4024], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4025], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4026], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4027], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4028], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4029], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4030], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4031], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4032], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4033], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4034], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4035], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4036], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4037], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4038], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4039], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4040], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4041], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4042], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4043], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4044], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4045], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4046], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4047], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4048], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4049], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4050], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4051], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4052], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4053], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4054], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4055], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4056], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4057], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4058], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4059], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4060], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4061], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4062], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4063], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4064], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4065], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4066], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4067], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4068], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4069], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4070], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4071], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4072], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4073], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4074], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4075], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4076], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4077], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4078], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4079], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4080], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4081], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4082], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4083], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4084], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4085], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4086], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4087], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4088], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4089], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4090], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4091], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4092], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4093], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4094], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4095], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4096], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4097], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4098], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4099], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4100], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4101], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4102], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4103], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4104], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4105], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4106], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4107], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4108], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4109], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4110], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4111], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4112], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4113], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4114], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4115], visible=True) # Move_Ship
        self.set_interact_object(trigger_ids=[10001046], state=1) # Wheel
        self.play_system_sound_in_box(box_ids=[102], sound='System_ShowGuideSummary_01')
        # 키를 작동시켜 배를 움직이면 다음 지역으로 넘어갈 수 있습니다
        self.show_guide_summary(entity_id=20031803, text_id=20031803)

    def on_tick(self) -> trigger_api.Trigger:
        if self.object_interacted(interact_ids=[10001046], state=0):
            return ShipMove02(self.ctx)


class ShipMove02(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_effect(trigger_ids=[6001], visible=True)
        self.hide_guide_summary(entity_id=20031803)
        self.set_user_value(trigger_id=1, key='ShipMove', value=1)
        self.set_breakable(trigger_ids=[4000], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4001], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4002], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4003], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4004], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4005], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4006], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4007], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4008], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4009], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4010], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4011], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4012], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4013], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4014], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4015], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4016], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4017], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4018], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4019], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4020], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4021], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4022], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4023], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4024], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4025], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4026], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4027], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4028], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4029], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4030], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4031], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4032], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4033], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4034], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4035], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4036], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4037], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4038], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4039], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4040], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4041], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4042], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4043], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4044], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4045], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4046], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4047], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4048], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4049], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4050], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4051], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4052], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4053], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4054], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4055], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4056], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4057], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4058], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4059], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4060], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4061], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4062], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4063], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4064], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4065], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4066], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4067], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4068], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4069], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4070], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4071], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4072], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4073], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4074], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4075], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4076], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4077], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4078], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4079], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4080], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4081], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4082], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4083], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4084], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4085], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4086], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4087], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4088], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4089], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4090], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4091], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4092], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4093], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4094], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4095], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4096], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4097], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4098], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4099], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4100], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4101], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4102], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4103], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4104], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4105], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4106], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4107], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4108], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4109], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4110], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4111], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4112], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4113], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4114], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4115], enable=True) # Move_Ship

    def on_tick(self) -> trigger_api.Trigger:
        if self.wait_tick(wait_tick=3000):
            return ShipMove03(self.ctx)


class ShipMove03(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_effect(trigger_ids=[6001], visible=False)
        self.set_skill(trigger_ids=[7000], enable=True)
        self.set_effect(trigger_ids=[6000], visible=True)

    def on_tick(self) -> trigger_api.Trigger:
        if self.wait_tick(wait_tick=19000):
            return ResetShip00(self.ctx)


class ResetShip00(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_interact_object(trigger_ids=[10001046], state=0) # Wheel
        self.set_breakable(trigger_ids=[4000], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4001], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4002], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4003], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4004], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4005], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4006], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4007], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4008], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4009], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4010], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4011], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4012], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4013], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4014], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4015], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4016], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4017], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4018], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4019], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4020], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4021], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4022], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4023], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4024], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4025], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4026], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4027], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4028], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4029], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4030], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4031], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4032], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4033], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4034], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4035], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4036], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4037], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4038], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4039], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4040], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4041], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4042], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4043], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4044], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4045], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4046], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4047], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4048], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4049], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4050], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4051], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4052], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4053], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4054], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4055], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4056], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4057], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4058], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4059], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4060], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4061], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4062], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4063], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4064], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4065], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4066], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4067], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4068], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4069], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4070], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4071], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4072], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4073], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4074], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4075], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4076], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4077], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4078], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4079], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4080], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4081], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4082], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4083], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4084], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4085], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4086], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4087], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4088], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4089], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4090], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4091], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4092], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4093], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4094], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4095], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4096], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4097], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4098], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4099], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4100], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4101], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4102], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4103], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4104], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4105], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4106], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4107], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4108], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4109], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4110], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4111], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4112], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4113], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4114], enable=False) # Move_Ship
        self.set_breakable(trigger_ids=[4115], enable=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4000], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4001], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4002], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4003], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4004], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4005], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4006], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4007], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4008], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4009], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4010], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4011], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4012], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4013], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4014], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4015], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4016], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4017], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4018], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4019], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4020], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4021], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4022], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4023], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4024], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4025], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4026], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4027], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4028], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4029], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4030], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4031], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4032], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4033], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4034], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4035], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4036], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4037], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4038], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4039], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4040], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4041], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4042], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4043], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4044], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4045], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4046], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4047], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4048], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4049], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4050], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4051], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4052], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4053], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4054], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4055], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4056], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4057], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4058], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4059], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4060], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4061], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4062], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4063], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4064], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4065], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4066], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4067], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4068], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4069], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4070], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4071], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4072], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4073], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4074], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4075], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4076], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4077], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4078], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4079], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4080], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4081], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4082], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4083], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4084], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4085], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4086], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4087], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4088], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4089], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4090], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4091], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4092], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4093], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4094], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4095], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4096], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4097], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4098], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4099], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4100], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4101], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4102], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4103], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4104], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4105], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4106], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4107], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4108], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4109], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4110], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4111], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4112], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4113], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4114], visible=False) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4115], visible=False) # Move_Ship

    def on_tick(self) -> trigger_api.Trigger:
        if self.wait_tick(wait_tick=2000):
            return ResetShip01(self.ctx)


class ResetShip01(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_visible_breakable_object(trigger_ids=[4000], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4001], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4002], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4003], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4004], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4005], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4006], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4007], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4008], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4009], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4010], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4011], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4012], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4013], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4014], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4015], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4016], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4017], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4018], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4019], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4020], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4021], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4022], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4023], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4024], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4025], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4026], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4027], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4028], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4029], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4030], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4031], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4032], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4033], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4034], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4035], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4036], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4037], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4038], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4039], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4040], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4041], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4042], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4043], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4044], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4045], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4046], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4047], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4048], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4049], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4050], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4051], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4052], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4053], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4054], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4055], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4056], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4057], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4058], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4059], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4060], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4061], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4062], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4063], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4064], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4065], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4066], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4067], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4068], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4069], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4070], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4071], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4072], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4073], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4074], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4075], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4076], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4077], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4078], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4079], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4080], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4081], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4082], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4083], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4084], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4085], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4086], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4087], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4088], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4089], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4090], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4091], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4092], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4093], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4094], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4095], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4096], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4097], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4098], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4099], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4100], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4101], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4102], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4103], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4104], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4105], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4106], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4107], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4108], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4109], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4110], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4111], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4112], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4113], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4114], visible=True) # Move_Ship
        self.set_visible_breakable_object(trigger_ids=[4115], visible=True) # Move_Ship
        self.set_interact_object(trigger_ids=[10001046], state=1) # Wheel

    def on_tick(self) -> trigger_api.Trigger:
        if self.object_interacted(interact_ids=[10001046], state=0):
            return ResetShip02(self.ctx)


class ResetShip02(trigger_api.Trigger):
    def on_enter(self) -> 'trigger_api.Trigger':
        self.set_breakable(trigger_ids=[4000], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4001], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4002], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4003], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4004], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4005], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4006], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4007], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4008], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4009], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4010], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4011], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4012], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4013], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4014], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4015], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4016], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4017], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4018], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4019], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4020], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4021], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4022], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4023], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4024], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4025], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4026], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4027], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4028], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4029], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4030], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4031], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4032], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4033], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4034], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4035], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4036], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4037], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4038], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4039], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4040], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4041], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4042], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4043], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4044], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4045], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4046], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4047], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4048], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4049], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4050], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4051], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4052], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4053], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4054], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4055], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4056], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4057], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4058], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4059], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4060], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4061], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4062], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4063], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4064], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4065], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4066], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4067], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4068], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4069], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4070], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4071], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4072], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4073], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4074], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4075], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4076], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4077], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4078], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4079], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4080], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4081], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4082], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4083], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4084], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4085], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4086], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4087], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4088], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4089], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4090], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4091], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4092], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4093], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4094], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4095], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4096], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4097], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4098], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4099], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4100], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4101], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4102], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4103], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4104], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4105], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4106], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4107], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4108], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4109], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4110], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4111], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4112], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4113], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4114], enable=True) # Move_Ship
        self.set_breakable(trigger_ids=[4115], enable=True) # Move_Ship

    def on_tick(self) -> trigger_api.Trigger:
        if self.wait_tick(wait_tick=24000):
            return ResetShip01(self.ctx)


initial_state = Setting
